### ISSUE TITLE
golang wasm tutorial

### ISSUE THREAD

**Issue by bashdrew** [aaronpowell/webpack-golang-wasm-async-loader#35]
I've followed your tutorial in https://www.aaron-powell.com/posts/2019-02-12-golang-wasm-6-typescript-react/ but it seems like the wasm function is not loading for me.  Below is what I added to the webpack.config.js:

        {
          test: /\.go$/,
          loader: 'golang-wasm-async-loader'
        },

The build is successful and the page is loading but it couldn't find the add() function. Am I missing something in the webpack.config.js file?  Thanks in advance.

```
App.tsx:25 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'apply')
    at c.<anonymous> (App.tsx:25:29)
    at s (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at a (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at c.<anonymous> (asyncToGenerator.js:21:12)
    at c.<anonymous> (App.tsx:22:5)
```

**Comment by aaronpowell** [comment]
what version of Go are you using? This repo is quite old and based on Go 1.12, current is 1.18 IIRC, so it's likely that the WASM stuff is different now and resulting in the error.

**Comment by bashdrew** [comment]
I really appreciate your response.  I am using go1.18.  Yes, it has a runtime error where it couldn't find the add() command.  The build is successful, though, and the main.wasm is generated.  It appears that WebAssembly.instantiate() isn't called at all.  I am fairly new to react.  May I know at what point does the default function in gobridge.js get called?  Is it during the 'import wasm from './main.go' '?  Thanks again.

**Comment by aaronpowell** [comment]
Yes, as soon as the `import` statement is hit it should run the initaliser that will setup everything.

**Comment by happybeing** [comment]
I forked and updated this some time ago up to Go 1.15 and others have forked that so you might have luck trying one of those, for example https://github.com/jriehl/webpack-golang-wasm-async-loader which claims to work with Go 1.16.

From memory things stabilised in Go at 1.16 so I recommend trying the above fork. I just didn't get around to updating my own fork. Good luck.

**Comment by bashdrew** [comment]
Thank you.  I will give it a try.
